# Generated by Django 2.2.24 on 2021-12-13 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0002_auto_20211122_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 17, 21, 43, 943995, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
