# Generated by Django 2.2.24 on 2021-12-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0006_auto_20211213_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='activation_key_expires',
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.PositiveIntegerField(verbose_name='возраст'),
        ),
        migrations.DeleteModel(
            name='ShopUserProfile',
        ),
    ]
